package vector

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"text/template"

	"github.com/stackit-mock/operator/api/v1alpha1"
)

// vectorConfigTmpl is the Go template that renders a complete Vector TOML
// configuration from a TelemetryRouter spec. This is the core of what the
// operator does — translating customer intent (CRD) into Vector reality (TOML).
//
// NOTE: Go template delimiters are changed to [[ ]] so that Vector's own
// {{ }} template syntax (used in Loki sink labels) can coexist without escaping.
const vectorConfigTmpl = `
# ── Generated by STACKIT Telemetry Operator ────────────────────────────────
# TelemetryRouter: [[ .Name ]] / [[ .Namespace ]]
# DO NOT EDIT MANUALLY — managed by the operator.

# ── API (required for readiness probe on :8686/health) ───────────────────────

[api]
enabled = true
address = "0.0.0.0:8686"

# ── Sources ─────────────────────────────────────────────────────────────────

[sources.otlp_in]
type = "opentelemetry"

[sources.otlp_in.grpc]
address = "0.0.0.0:4317"

[sources.otlp_in.http]
address = "0.0.0.0:4318"

# ── Internal metrics source (exposes Vector's own health metrics) ─────────

[sources.vector_metrics]
type = "internal_metrics"

# ── Enrichment Transform (logs + traces only) ────────────────────────────────
# Metrics are excluded here because Vector metric events have a different
# internal structure — VRL field assignments like .resource.attributes.*
# do not apply to metric events and will error at runtime.

[transforms.enrich]
type   = "remap"
inputs = ["otlp_in.logs", "otlp_in.traces"]
source = '''
  # Standard enrichment — added by operator to every TelemetryRouter
  .resource.attributes."deployment.environment" = "local"
  .resource.attributes."k8s.cluster"            = "docker-desktop"
  .resource.attributes."telemetry.router.name"  = "[[ .Name ]]"

  # Hoist service.name to a top-level field so Loki sink labels can reference it.
  # Vector's Loki label templates use {{ field }} syntax (flat field names only).
  # Try multiple paths: Vector may store dotted OTel keys as nested objects
  # (.resource.attributes.service.name) instead of quoted literal keys.
  sn = .resource.attributes."service.name"
  if is_null(sn) { sn = .resource.attributes.service.name }
  if is_null(sn) { sn = .attributes.otelServiceName }
  .service_name = if !is_null(sn) { to_string!(sn) } else { "unknown" }
[[- range .Transforms ]]
  # Transform: [[ .Name ]]
  [[ .VRL ]]
[[- end ]]
'''

# ── Sinks ────────────────────────────────────────────────────────────────────
# All enriched events (logs + traces) flow directly from [enrich].
# Vector internal metrics flow from [vector_metrics].
# No route transform needed — the opentelemetry source only emits logs/traces.
[[- range .Destinations ]]

[[- if eq .Type "LOKI" ]]
[sinks.sink_[[ .Name | sanitize ]]]
type     = "loki"
inputs   = ["enrich"]
endpoint = "[[ .Endpoint ]]"
encoding.codec = "json"

[sinks.sink_[[ .Name | sanitize ]].labels]
router       = "[[ .Name | sanitize ]]"
service_name = "{{ service_name }}"

[sinks.sink_[[ .Name | sanitize ]].buffer]
type       = "memory"
max_events = 50000
when_full  = "drop_newest"

[[- else if eq .Type "PROMETHEUS" ]]
[sinks.sink_[[ .Name | sanitize ]]]
type     = "prometheus_remote_write"
inputs   = ["vector_metrics"]
endpoint = "[[ .Endpoint ]]"

[sinks.sink_[[ .Name | sanitize ]].healthcheck]
enabled = false

[sinks.sink_[[ .Name | sanitize ]].buffer]
type       = "memory"
max_events = 50000
when_full  = "drop_newest"

[[- else if eq .Type "OTLP" ]]
[sinks.sink_[[ .Name | sanitize ]]]
type     = "http"
inputs   = ["enrich"]
uri      = "[[ .Endpoint ]]/v1/traces"
method   = "post"
encoding.codec = "json"

[sinks.sink_[[ .Name | sanitize ]].request.headers]
Content-Type = "application/json"

[sinks.sink_[[ .Name | sanitize ]].buffer]
type       = "memory"
max_events = 50000
when_full  = "drop_newest"

[[- end ]]
[[- end ]]
`

type configData struct {
	Name         string
	Namespace    string
	Transforms   []v1alpha1.VRLTransform
	Destinations []v1alpha1.Destination
}

// sanitize is a template function that makes a string safe for use as a TOML key.
func sanitize(s string) string {
	out := make([]byte, 0, len(s))
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' {
			out = append(out, byte(c))
		} else {
			out = append(out, '_')
		}
	}
	return string(out)
}

// Render produces the Vector TOML config string from a TelemetryRouter spec.
func Render(tr *v1alpha1.TelemetryRouter) (string, error) {
	funcMap := template.FuncMap{
		"sanitize": sanitize,
	}

	// Use [[ ]] as Go template delimiters so Vector's own {{ }} template syntax
	// (used in Loki sink label values) can appear literally in the output.
	tmpl, err := template.New("vector").Delims("[[", "]]").Funcs(funcMap).Parse(vectorConfigTmpl)
	if err != nil {
		return "", fmt.Errorf("parsing vector config template: %w", err)
	}

	data := configData{
		Name:         tr.Name,
		Namespace:    tr.Namespace,
		Transforms:   tr.Spec.Transforms,
		Destinations: tr.Spec.Destinations,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing vector config template: %w", err)
	}

	return buf.String(), nil
}

// Hash returns a short content hash of the rendered config.
// The operator stores this in the CRD status to detect drift.
func Hash(config string) string {
	sum := sha256.Sum256([]byte(config))
	return fmt.Sprintf("%x", sum[:6])
}
