package vector

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"net/url"
	"text/template"

	"github.com/stackit-mock/operator/api/v1alpha1"
)

// vectorConfigTmpl is the Go template that renders a complete Vector TOML
// configuration from a TelemetryRouter spec.
//
// Signal routing (Vector 0.51.1+):
//   - Logs    → enrich (VRL) → loki sink
//   - Traces  → opentelemetry sink ([encoding] codec=otlp) → Tempo
//   - Metrics → opentelemetry sink ([encoding] codec=otlp) → Prometheus OTLP receiver
//   - Vector pipeline metrics → prometheus_remote_write sink
//
// NOTE: Go template delimiters are [[ ]] so Vector's own {{ }} label templates
// can appear literally in the output without escaping.
const vectorConfigTmpl = `
# ── Generated by STACKIT Telemetry Operator ────────────────────────────────
# TelemetryRouter: [[ .Name ]] / [[ .Namespace ]]
# Vector: 0.53.0  (opentelemetry sink + otlp codec)
# DO NOT EDIT MANUALLY — managed by the operator.

# ── API (required for readiness probe on :8686/health) ───────────────────────

[api]
enabled = true
address = "0.0.0.0:8686"

# ── Sources ──────────────────────────────────────────────────────────────────
# opentelemetry source exposes three named outputs in Vector 0.43+:
#   otlp_in.logs    — OTel log records
#   otlp_in.traces  — OTel trace spans
#   otlp_in.metrics — OTel metrics (Vector 0.44+)

[sources.otlp_in]
type = "opentelemetry"

[sources.otlp_in.grpc]
address = "0.0.0.0:4317"

[sources.otlp_in.http]
address = "0.0.0.0:4318"

# Vector's own internal pipeline metrics (buffer depth, events/s, errors)
[sources.vector_metrics]
type = "internal_metrics"

# ── Enrichment Transform (logs only) ─────────────────────────────────────────
# Only log events pass through VRL enrichment.
# Traces and metrics are forwarded directly via opentelemetry sinks below,
# preserving the original OTLP encoding with zero-copy fidelity.

[transforms.enrich]
type   = "remap"
inputs = ["otlp_in.logs"]
source = '''
  # Standard enrichment — added by operator to every TelemetryRouter
  .resource.attributes."deployment.environment" = "local"
  .resource.attributes."k8s.cluster"            = "docker-desktop"
  .resource.attributes."telemetry.router.name"  = "[[ .Name ]]"

  # Hoist service.name to a top-level field so Loki sink labels can reference it.
  # Vector's Loki label templates use {{ field }} syntax (flat field names only).
  # Try multiple paths: Vector may store dotted OTel keys as nested objects.
  sn = .resource.attributes."service.name"
  if is_null(sn) { sn = .resource.attributes.service.name }
  if is_null(sn) { sn = .attributes.otelServiceName }
  .service_name = if !is_null(sn) { to_string!(sn) } else { "unknown" }
[[- range .Transforms ]]
  # Transform: [[ .Name ]]
  [[ .VRL ]]
[[- end ]]
'''

# ── Sinks ─────────────────────────────────────────────────────────────────────
[[- range .Destinations ]]

[[- if eq .Type "LOKI" ]]
# ── Loki sink — enriched log events ──────────────────────────────────────────
[sinks.sink_[[ .Name | sanitize ]]]
type     = "loki"
inputs   = ["enrich"]
endpoint = "[[ .Endpoint ]]"
encoding.codec = "json"

[sinks.sink_[[ .Name | sanitize ]].labels]
router       = "[[ .Name | sanitize ]]"
service_name = "{{ service_name }}"

[sinks.sink_[[ .Name | sanitize ]].buffer]
type       = "memory"
max_events = 50000
when_full  = "drop_newest"

[[- else if eq .Type "PROMETHEUS" ]]
# ── Prometheus sink (Vector internal metrics via remote_write) ────────────────
[sinks.sink_[[ .Name | sanitize ]]]
type     = "prometheus_remote_write"
inputs   = ["vector_metrics"]
endpoint = "[[ .Endpoint ]]"

[sinks.sink_[[ .Name | sanitize ]].healthcheck]
enabled = false

[sinks.sink_[[ .Name | sanitize ]].buffer]
type       = "memory"
max_events = 50000
when_full  = "drop_newest"

# ── Prometheus sink (app OTel metrics via OTLP receiver) ─────────────────────
# Disabled on Vector 0.53 because opentelemetry sink does not accept metrics (logs/traces only).
# Remove this block once Vector version supports metric egress via opentelemetry sink.
[[- else if eq .Type "OTLP" ]]
# ── OTLP sink — traces forwarded as native OTLP (Vector 0.51+ opentelemetry sink)
[sinks.sink_[[ .Name | sanitize ]]]
type   = "opentelemetry"
inputs = ["otlp_in.traces"]

[sinks.sink_[[ .Name | sanitize ]].protocol]
type = "http"
uri  = "[[ .Endpoint ]]/v1/traces"

encoding.codec = "otlp"

[sinks.sink_[[ .Name | sanitize ]].buffer]
type       = "memory"
max_events = 50000
when_full  = "drop_newest"

[[- end ]]
[[- end ]]
`

type configData struct {
	Name         string
	Namespace    string
	Transforms   []v1alpha1.VRLTransform
	Destinations []v1alpha1.Destination
}

// sanitize makes a string safe for use as a TOML key.
func sanitize(s string) string {
	out := make([]byte, 0, len(s))
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' {
			out = append(out, byte(c))
		} else {
			out = append(out, '_')
		}
	}
	return string(out)
}

// prometheusBase strips the path from a Prometheus remote_write endpoint URL
// and returns just the scheme+host, used to derive the OTLP receiver endpoint.
// e.g. "http://prometheus:9090/api/v1/write" → "http://prometheus:9090"
func prometheusBase(endpoint string) string {
	u, err := url.Parse(endpoint)
	if err != nil {
		return endpoint
	}
	return fmt.Sprintf("%s://%s", u.Scheme, u.Host)
}

// Render produces the Vector TOML config string from a TelemetryRouter spec.
func Render(tr *v1alpha1.TelemetryRouter) (string, error) {
	funcMap := template.FuncMap{
		"sanitize":       sanitize,
		"prometheusBase": prometheusBase,
	}

	// Use [[ ]] as Go template delimiters so Vector's own {{ }} template syntax
	// (used in Loki sink label values) can appear literally in the output.
	tmpl, err := template.New("vector").Delims("[[", "]]").Funcs(funcMap).Parse(vectorConfigTmpl)
	if err != nil {
		return "", fmt.Errorf("parsing vector config template: %w", err)
	}

	data := configData{
		Name:         tr.Name,
		Namespace:    tr.Namespace,
		Transforms:   tr.Spec.Transforms,
		Destinations: tr.Spec.Destinations,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing vector config template: %w", err)
	}

	return buf.String(), nil
}

// Hash returns a short content hash of the rendered config.
// The operator stores this in the CRD status to detect drift.
func Hash(config string) string {
	sum := sha256.Sum256([]byte(config))
	return fmt.Sprintf("%x", sum[:6])
}
